[15:50:25|29-11-21] FATAL ERROR: Traceback (most recent call last):
  File "main.py", line 296, in <module>
    exec(code) # запуск всего кода который мы прочитали из файлов
  File "<string>", line 19
    3image_pyglet.anchor_x = image_pyglet.width // 2
                ^
SyntaxError: invalid syntax

[18:54:29|04-12-21] FATAL ERROR: Traceback (most recent call last):
  File "main.py", line 263, in <module>
    file = load_obj('objects')
  File "main.py", line 261, in load_obj
    return pickle.load(f)
AttributeError: Can't get attribute 'File' on <module '__main__' (built-in)>

[18:55:25|04-12-21] FATAL ERROR: Traceback (most recent call last):
  File "main.py", line 263, in <module>
    file = load_obj('objects')
  File "main.py", line 261, in load_obj
    return pickle.load(f)
AttributeError: Can't get attribute 'File' on <module '__main__' (built-in)>

[18:56:11|04-12-21] FATAL ERROR: Traceback (most recent call last):
  File "main.py", line 263, in <module>
    file = load_obj('objects')
  File "main.py", line 261, in load_obj
    return pickle.load(f)
AttributeError: Can't get attribute 'File' on <module '__main__' from 'main.py'>

[18:57:56|04-12-21] FATAL ERROR: Traceback (most recent call last):
  File "main.py", line 263, in <module>
    file = load_obj('objects')
  File "main.py", line 261, in load_obj
    return pickle.load(f)
AttributeError: Can't get attribute 'File' on <module '__main__' from 'main.py'>

[18:58:46|04-12-21] FATAL ERROR: Traceback (most recent call last):
  File "main.py", line 263, in <module>
    file = load_obj('objects')
  File "main.py", line 261, in load_obj
    return pickle.load(f)
AttributeError: Can't get attribute 'File' on <module '__main__' from 'main.py'>

[18:59:09|04-12-21] FATAL ERROR: Traceback (most recent call last):
  File "main.py", line 263, in <module>
    file = load_obj('objects')
  File "main.py", line 261, in load_obj
    return pickle.load(f)
AttributeError: Can't get attribute 'File' on <module '__main__' from 'main.py'>

[19:01:39|04-12-21] FATAL ERROR: Traceback (most recent call last):
  File "main.py", line 263, in <module>
    file = load_obj('objects')
  File "main.py", line 261, in load_obj
    return pickle.load(f)
AttributeError: Can't get attribute 'File' on <module '__main__' from 'main.py'>

[19:04:42|04-12-21] FATAL ERROR: Traceback (most recent call last):
  File "main.py", line 263, in <module>
    file = load_obj('objects')
  File "main.py", line 261, in load_obj
    return pickle.load(f)
AttributeError: Can't get attribute 'File' on <module '__main__' from 'main.py'>

[19:04:51|04-12-21] FATAL ERROR: Traceback (most recent call last):
  File "main.py", line 263, in <module>
    file = load_obj('objects')
  File "main.py", line 261, in load_obj
    return pickle.load(f)
AttributeError: Can't get attribute 'File' on <module '__main__' from 'main.py'>

[19:05:00|04-12-21] FATAL ERROR: Traceback (most recent call last):
  File "main.py", line 263, in <module>
    file1 = load_obj('objects')
  File "main.py", line 261, in load_obj
    return pickle.load(f)
AttributeError: Can't get attribute 'File' on <module '__main__' from 'main.py'>

[19:05:23|04-12-21] FATAL ERROR: Traceback (most recent call last):
  File "main.py", line 263, in <module>
    file = load_obj('objects')
  File "main.py", line 261, in load_obj
    return pickle.load(f)
AttributeError: Can't get attribute 'file_code' on <module '__main__' from 'main.py'>

[19:05:54|04-12-21] FATAL ERROR: Traceback (most recent call last):
  File "main.py", line 263, in <module>
    file = load_obj('objects')
  File "main.py", line 261, in load_obj
    return pickle.load(f)
AttributeError: Can't get attribute 'file_code' on <module '__main__' from 'main.py'>

[19:06:25|04-12-21] FATAL ERROR: Traceback (most recent call last):
  File "main.py", line 264, in <module>
    file = load_obj('objects')
  File "main.py", line 262, in load_obj
    return pickle.load(f)
AttributeError: Can't get attribute 'file_code' on <module '__main__' from 'main.py'>

[19:06:51|04-12-21] FATAL ERROR: Traceback (most recent call last):
  File "main.py", line 263, in <module>
    file = load_obj('objects')
  File "main.py", line 261, in load_obj
    return pickle.load(f)
AttributeError: Can't get attribute 'file_code' on <module '__main__' from 'main.py'>

[19:07:08|04-12-21] FATAL ERROR: Traceback (most recent call last):
  File "main.py", line 263, in <module>
    print(file = load_obj('objects'))
  File "main.py", line 261, in load_obj
    return pickle.load(f)
AttributeError: Can't get attribute 'file_code' on <module '__main__' from 'main.py'>

[19:07:24|04-12-21] FATAL ERROR: Traceback (most recent call last):
  File "main.py", line 265, in <module>
    file = load_obj_file('objects')
  File "main.py", line 244, in load_obj_file
    return pickle.load(f)
AttributeError: Can't get attribute 'file_code' on <module '__main__' from 'main.py'>

[19:08:22|04-12-21] FATAL ERROR: Traceback (most recent call last):
  File "main.py", line 264, in <module>
    file = load_obj_file('objects')
  File "main.py", line 245, in load_obj_file
    return pickle.load(f)
AttributeError: Can't get attribute 'file_code' on <module '__main__' from 'main.py'>

[19:08:39|04-12-21] FATAL ERROR: Traceback (most recent call last):
  File "main.py", line 263, in <module>
    file = load_obj_file('objects')
  File "main.py", line 244, in load_obj_file
    return pickle.load(f)
AttributeError: Can't get attribute 'file_code' on <module '__main__' from 'main.py'>

[19:13:55|04-12-21] FATAL ERROR: Traceback (most recent call last):
  File "main.py", line 263, in <module>
    file = load_obj_file('objects')
  File "main.py", line 244, in load_obj_file
    return pickle.load(f)
AttributeError: Can't get attribute 'file_code' on <module '__main__' from 'main.py'>

[19:14:02|04-12-21] FATAL ERROR: Traceback (most recent call last):
  File "main.py", line 263, in <module>
    file = load_obj_file('objects')
  File "main.py", line 244, in load_obj_file
    return pickle.load(f)
AttributeError: Can't get attribute 'file_code' on <module '__main__' from 'main.py'>

[19:16:17|04-12-21] FATAL ERROR: Traceback (most recent call last):
  File "main.py", line 263, in <module>
    for i in range(len(files)): #
  File "main.py", line 261, in load_obj
AttributeError: Can't get attribute 'file_code' on <module '__main__' (built-in)>

[19:16:21|04-12-21] FATAL ERROR: Traceback (most recent call last):
  File "main.py", line 263, in <module>
    for i in range(len(files)): #
  File "main.py", line 261, in load_obj
AttributeError: Can't get attribute 'file_code' on <module '__main__' (built-in)>

[13:26:32|05-12-21] FATAL ERROR: Traceback (most recent call last):
  File "main.py", line 312, in <module>
    exec(code) # запуск всего кода который мы прочитали из файлов
  File "<string>", line 2304
    if bullet[3] == -90
                      ^
SyntaxError: invalid syntax

[13:40:53|05-12-21] FATAL ERROR: Traceback (most recent call last):
  File "main.py", line 312, in <module>
    exec(code) # запуск всего кода который мы прочитали из файлов
  File "<string>", line 2319
SyntaxError: can't assign to function call

[13:41:10|05-12-21] FATAL ERROR: Traceback (most recent call last):
  File "main.py", line 312, in <module>
    exec(code) # запуск всего кода который мы прочитали из файлов
  File "<string>", line 2319
SyntaxError: can't assign to function call

[13:45:28|05-12-21] FATAL ERROR: Traceback (most recent call last):
  File "main.py", line 312, in <module>
    exec(code) # запуск всего кода который мы прочитали из файлов
  File "<string>", line 2319
SyntaxError: can't assign to function call

[20:32:49|05-12-21] FATAL ERROR: Traceback (most recent call last):
  File "main.py", line 312, in <module>
    exec(code) # запуск всего кода который мы прочитали из файлов
  File "<string>", line 2319
SyntaxError: can't assign to function call

[20:34:41|05-12-21] FATAL ERROR: Traceback (most recent call last):
  File "main.py", line 312, in <module>
    exec(code) # запуск всего кода который мы прочитали из файлов
  File "<string>", line 2319
SyntaxError: can't assign to function call

[20:37:04|05-12-21] FATAL ERROR: Traceback (most recent call last):
  File "main.py", line 312, in <module>
    exec(code) # запуск всего кода который мы прочитали из файлов
  File "<string>", line 2318
    if get_obj_display('world').map_wall[get_obj_display('world').get_block_num(0, 0] != 'none':
                                                                                    ^
SyntaxError: invalid syntax

[20:41:05|05-12-21] FATAL ERROR: Traceback (most recent call last):
  File "main.py", line 312, in <module>
    exec(code) # запуск всего кода который мы прочитали из файлов
  File "<string>", line 2318
    if (bullet[1] > settings.width)
                                  ^
SyntaxError: invalid syntax

[20:41:23|05-12-21] FATAL ERROR: Traceback (most recent call last):
  File "main.py", line 312, in <module>
    exec(code) # запуск всего кода который мы прочитали из файлов
  File "<string>", line 2318
    if (bullet[1] > settings.width) or
                                     ^
SyntaxError: invalid syntax

[20:41:30|05-12-21] FATAL ERROR: Traceback (most recent call last):
  File "main.py", line 312, in <module>
    exec(code) # запуск всего кода который мы прочитали из файлов
  File "<string>", line 2318
    if (bullet[1] > settings.width) or
                                     ^
SyntaxError: invalid syntax

[20:41:36|05-12-21] FATAL ERROR: Traceback (most recent call last):
  File "main.py", line 312, in <module>
    exec(code) # запуск всего кода который мы прочитали из файлов
  File "<string>", line 2318
    if (bullet[1] > settings.width) or
                                     ^
SyntaxError: invalid syntax

[21:24:27|05-12-21] FATAL ERROR: Traceback (most recent call last):
  File "main.py", line 312, in <module>
    exec(code) # запуск всего кода который мы прочитали из файлов
  File "<string>", line 2231
    class player():
        ^
SyntaxError: invalid syntax

[21:24:51|05-12-21] FATAL ERROR: Traceback (most recent call last):
  File "main.py", line 312, in <module>
    exec(code) # запуск всего кода который мы прочитали из файлов
  File "<string>", line 2231
    class player():
        ^
SyntaxError: invalid syntax

[21:25:56|05-12-21] FATAL ERROR: Traceback (most recent call last):
  File "main.py", line 312, in <module>
    exec(code) # запуск всего кода который мы прочитали из файлов
  File "<string>", line 2231
    class player():
        ^
SyntaxError: invalid syntax

[21:45:53|05-12-21] FATAL ERROR: Traceback (most recent call last):
  File "main.py", line 312, in <module>
    exec(code) # запуск всего кода который мы прочитали из файлов
  File "<string>", line 2150
    (settings.height - self.image_wall.height) / 2) + y * self.size_poligon + self.size_poligon/2), array_pol)
                                                                                                 ^
SyntaxError: invalid syntax

[21:46:01|05-12-21] FATAL ERROR: Traceback (most recent call last):
  File "main.py", line 312, in <module>
    exec(code) # запуск всего кода который мы прочитали из файлов
  File "<string>", line 2150
    y * self.size_poligon + self.size_poligon/2), array_pol)
                                                           ^
SyntaxError: invalid syntax

[22:16:47|05-12-21] FATAL ERROR: Traceback (most recent call last):
  File "main.py", line 312, in <module>
    exec(code) # запуск всего кода который мы прочитали из файлов
  File "<string>", line 2324
    try:
      ^
IndentationError: expected an indented block

[22:27:17|05-12-21] FATAL ERROR: Traceback (most recent call last):
  File "main.py", line 312, in <module>
    exec(code) # запуск всего кода который мы прочитали из файлов
  File "<string>", line 2355
    except except as e:
                ^
SyntaxError: invalid syntax

[11:28:15|06-12-21] FATAL ERROR: Traceback (most recent call last):
  File "main.py", line 312, in <module>
    exec(code) # запуск всего кода который мы прочитали из файлов
  File "<string>", line 2278
    speed_tick = (self.check_fps/pyglet.clock.get_fps() if pyglet.clock.get_fps()<= self.norm_fps else 1) * self.speed_tick)
                                                                                                                           ^
SyntaxError: invalid syntax

[15:36:55|07-12-21] FATAL ERROR: Traceback (most recent call last):
  File "main.py", line 312, in <module>
    exec(code) # запуск всего кода который мы прочитали из файлов
  File "<string>", line 2434
    speed_tick = (self.check_fps / pyglet.clock.get_fps() if pyglet.clock.get_fps() <= else 1) * bullet[4]
                                                                                          ^
SyntaxError: invalid syntax

[18:19:21|09-12-21] FATAL ERROR: Traceback (most recent call last):
  File "main.py", line 312, in <module>
    exec(code) # запуск всего кода который мы прочитали из файлов
  File "<string>", line 2323
    if (eval('keyboard[key.' + KEY_BINDS['P' + str(self.id+1)]['left'] + ']') and not self.bot) or (self.bot and ):
                                                                                                                 ^
SyntaxError: invalid syntax

[18:21:19|09-12-21] FATAL ERROR: Traceback (most recent call last):
  File "main.py", line 312, in <module>
    exec(code) # запуск всего кода который мы прочитали из файлов
  File "<string>", line 2327
    if (eval('keyboard[key.' + KEY_BINDS['P' + str(self.id+1)]['left'] + ']') and not self.bot) or (self.bot and rotation = -90):
                                                                                                                          ^
SyntaxError: invalid syntax

[18:21:23|09-12-21] FATAL ERROR: Traceback (most recent call last):
  File "main.py", line 312, in <module>
    exec(code) # запуск всего кода который мы прочитали из файлов
  File "<string>", line 2327
    if (eval('keyboard[key.' + KEY_BINDS['P' + str(self.id+1)]['left'] + ']') and not self.bot) or (self.bot and rotation = -90):
                                                                                                                          ^
SyntaxError: invalid syntax

